name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine

      - name: Build package
        run: |
          echo "Python version: ${{ matrix.python-version }}"
          echo "Python major version: ${{ str(matrix.python-version)[0] }}"
          echo "Python minor version: ${{ matrix.python-version[2:] }}"
          python setup.py bdist_wheel --python-tag=py${{ matrix.python-version[0:1] }}${{ matrix.python-version[2:] }}

      - name: Save package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkZTliOGEzYmMtZjBkZi00ZmMxLWI2MzEtZjkxMzcxZGJjNGQ4AAITWzEsWyJ2bC1kYXRhc2V0cyJdXQACLFsyLFsiY2E2NGMxMjQtMTgzNS00YjVlLTg5YmYtOGY0OTNjOTYyN2E5Il1dAAAGIJcUsbr3opBgMqpVFIwq4vMpsmccCopgpbZDNpGJiAm-# ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
