name: Build

# on:
#   release:
#     types: [created]
    
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine

      - name: Build package
        run: |
          #python setup.py bdist_wheel --python-tag=py${{ matrix.python-version }}
          
          python setup.py sdist bdist_wheel
          
          # get distribution and version from setup.py
          distribution=$(python setup.py --name)
          version=$(python setup.py --version)
          
          # get python version and implementation
          python_version=$(python -c "import platform; print(platform.python_version())")
          implementation=$(python -c "import platform; print(platform.python_implementation())")
          
          # construct python tag
          python_tag="${implementation}${python_version//./}"
          
          # get platform tag
          platform_tag=$(python -c "from distutils.util import get_platform; print(get_platform().replace('-', '_').replace('.', '_'))")
          
          # construct new filename
          new_filename="${distribution}-${version}-${python_tag}-${platform_tag}.whl"
          
          # rename the .whl file to the new filename
          mv dist/*.whl dist/$new_filename

      - name: Save package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkZTliOGEzYmMtZjBkZi00ZmMxLWI2MzEtZjkxMzcxZGJjNGQ4AAITWzEsWyJ2bC1kYXRhc2V0cyJdXQACLFsyLFsiY2E2NGMxMjQtMTgzNS00YjVlLTg5YmYtOGY0OTNjOTYyN2E5Il1dAAAGIJcUsbr3opBgMqpVFIwq4vMpsmccCopgpbZDNpGJiAm-# ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
