name: Build

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build wheels
        run: |
          python setup.py bdist_wheel --dist-dir dist/
          
          # Include the OS name in the filename of the wheel
          mv dist/*.whl dist/vl-datasets-${{ matrix.os }}.whl

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: 'visual-layer' #${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: 'TQD.$kU#WtsNh3@' #${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
