name: Build and Publish on PyPI

on: [push]
# on:
#   release:
#     types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine

      - name: Build package
        run: |
          python setup.py bdist_wheel --python-tag=py${{ matrix.python-version }} --plat-name=${{ matrix.os }}
      
      - name: Rename wheel files
        run: |
          for file in dist/*.whl; do
            filename=$(basename "$file")
            project_name=$(echo "$filename" | cut -d'-' -f1)
            version=$(echo "$filename" | cut -d'-' -f2)
            python_tag=$(echo "$filename" | cut -d'-' -f3)
            abi=$(echo "$filename" | cut -d'-' -f4)
            platform=$(python -c "import distutils.util; print(distutils.util.get_platform())")

            new_filename="$project_name-$version-$python_tag-$abi-$platform.whl"
            mv "$file" "dist/$new_filename"
          done
      
      - name: Save package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
