name: Build and Publish to PyPI

on: [push]

jobs:
  build_wheels:
    name: Build wheels on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build SDist and wheel
        run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

      - name: Check metadata
        run: pipx run twine check dist/*

# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ['3.9', '3.10']
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install wheel setuptools twine

#       - name: Build package
#         run: |
#           python setup.py bdist_wheel --python-tag=py${{ matrix.python-version }}
      

#       - name: Save package artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: dist
#           path: dist/

#   publish:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download package artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: dist
#           path: dist/

#       - name: Publish distribution 📦 to PyPI
#         if: startsWith(github.ref, 'refs/tags')
#         uses: pypa/gh-action-pypi-publish@v1.8.6
#         with:
#           password: ${{ secrets.PYPI_API_TOKEN }}
