name: Build and Publish to PyPI

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY=1
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ['3.9', '3.10']
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install wheel setuptools twine

#       - name: Build package
#         run: |
#           python setup.py bdist_wheel --python-tag=py${{ matrix.python-version }}
      

#       - name: Save package artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: dist
#           path: dist/

#   publish:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download package artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: dist
#           path: dist/

#       - name: Publish distribution 📦 to PyPI
#         if: startsWith(github.ref, 'refs/tags')
#         uses: pypa/gh-action-pypi-publish@v1.8.6
#         with:
#           password: ${{ secrets.PYPI_API_TOKEN }}
