name: Smoke Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
    test_imports:
      runs-on: ${{ matrix.os }}
      env:
        SENTRY_OPT_OUT: True
      strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
           fetch-depth: 0
  
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .
        
        - name: Test imports
          run: |
            echo "Sentry opt out: "
            echo $SENTRY_OPT_OUT
            python .github/workflows/test_imports.py
      
